### ISSUE TITLE
[Question] Would this work for APK files?

### ISSUE THREAD

**Issue by Morsmalleo** [mauricelambert/ZipSteganograPy#1]
Would this work for APK files considering these are basically just zip files anyway??

**Comment by mauricelambert** [comment]
Hi ! Thanks for your question.

It's possible to hide your APK file in PNG file with this tool because APK file is a ZIP file ([source on stackoverflow](https://stackoverflow.com/questions/15934674/is-there-a-difference-between-typical-a-zip-file-and-an-apk-file#answers-header)).

**Comment by Morsmalleo** [comment]
Awesome thank you 👍🙂
